name: Run tests

on: 
  push:
    branches:
      - main
      - features/**
  
  pull_request:
    branches:
      - main
  
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #checkout the repository
      - name: checkout code
      - uses: actions/checkout@v3
     
      # Install bun
      -name: Install Bun
      run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::$(bun bin)"
  
      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run tests
      - name: Run tests
        run: bun test